py/oa-gae/branches/django/site_improve/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('',
     (r'^$', 'oa.site_improve.views.bug_index'),
     (r'^!edit$', 'oa.site_improve.views.bug_edit'),
     (r'^(?P<object_id>\d+)$', 'oa.site_improve.views.bug_detail'),
     
     (r'^my/$', 'oa.site_improve.views.bug_my'),
     (r'^open/$', 'oa.site_improve.views.bug_open'),
)

py/oa-gae/branches/django/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template,redirect_to
from django.shortcuts import render_to_response
from django.template import RequestContext

def _404(request):
    return render_to_response('404.html', context_instance=RequestContext(request))
def _500():
    return render_to_response('500.html', context_instance=RequestContext(request))

handler404 = 'oa.urls._404'
handler500 = 'oa.urls._500'

url_prefix = ''
if settings.CONTEXT_PATH:
    url_prefix = (settings.CONTEXT_PATH)[1:]+'/'  

urlpatterns = patterns('',
    # Example:
    # (r'^oa/', include('oa.foo.urls')),

    # Uncomment this for admin:
    (r'^%sadmin/'%url_prefix, include('django.contrib.admin.urls')),
    
    (r'^%si18n.js$'%url_prefix, direct_to_template, {'template': 'js_i18n.html', 'mimetype':'text/javascript'}),
    
    (r'^%scontext_path.js$'%url_prefix, direct_to_template, {'template': 'js_context_path.html', 'mimetype':'text/javascript'}),
    
    (r'^%saccounts/login$'%url_prefix, 'django.contrib.auth.views.login',{'template_name': 'accounts/login.html'}),
    
    (r'^%saccounts/logout$'%url_prefix, 'django.contrib.auth.views.logout',{'next_page': settings.LOGOUT_REDIRECT_URL}),
    (r'^%saccounts/password_change$'%url_prefix, 'django.contrib.auth.views.password_change',{'template_name': 'accounts/password_change_form.html'}),
    (r'^%saccounts/password_changedone/$'%url_prefix, 'django.contrib.auth.views.password_change_done',{'template_name': 'accounts/password_change_done.html'}),
    (r'^%si18n/setlang'%url_prefix, 'django.views.i18n.set_language'),
   
    (r'^%s$'%url_prefix, redirect_to,{'url': 'work_note/'}),
    
    (r'^%swork_note/'%url_prefix, include('oa.work_note.urls')),
    (r'^%ssite_improve/'%url_prefix, include('oa.site_improve.urls')),
    
)

if settings.CONTEXT_PATH:
    urlpatterns += patterns('',
        (r'^$', redirect_to, {'url': settings.CONTEXT_PATH+'/    '}),
    )



if settings.MEDIA_ROOT and settings.DEBUG:
    urlpatterns += patterns('',
        (r'^s/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

py/oa-gae/branches/django/site_improve/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy as gettext_lazy
# Create your models here.

bug_status_choices = (('open', gettext_lazy('open')), ('fixed', gettext_lazy('fixed')), ('reopen', gettext_lazy('reopen')), ('closed', gettext_lazy('closed')),)

class Bug(models.Model):
    current_content = models.ForeignKey('Content',null=True,related_name='ref_bug')
    def __unicode__(self):
        return self.current_content.summary;
    class Admin:
        pass;
    class Meta:
        verbose_name = gettext_lazy('Bug');
        verbose_name_plural = gettext_lazy('Bugs');
        ordering = ['-current_content']
    
class Content(models.Model):
    summary = models.CharField(gettext_lazy('Summary'), max_length=200)
    type=models.CharField(gettext_lazy('Type'), max_length=20, choices=(('defect', gettext_lazy('defect')), ('enhancement', gettext_lazy('enhancement')), ('task', gettext_lazy('task')),), default='defect')
    content = models.TextField(gettext_lazy('Content'), blank=True, null=True)
    priority=models.CharField(gettext_lazy('Priority'), max_length=20, choices=(('blocker', gettext_lazy('blocker')), ('critical', gettext_lazy('critical')), ('major', gettext_lazy('major')), ('minor', gettext_lazy('minor')), ('trivial', gettext_lazy('trivial')),), default='major')
    assign_to =  models.CharField(gettext_lazy('Assign to'), max_length=200, blank=True, null=True)
    cc =  models.CharField(gettext_lazy('Cc'), max_length=200, blank=True, null=True)
    keywords = models.CharField(gettext_lazy('Keywords'), max_length=200, blank=True, null=True)
    component = models.CharField(gettext_lazy('Component'), max_length=200, choices=(('work_note', gettext_lazy('work_note')), ('site_improve', gettext_lazy('site_improve')),), default='work note')
#    version = models.CharField(gettext_lazy('Version'), max_length=200, choices=(('trunk', gettext_lazy('trunk'))), default='trunk')
    version = models.CharField(gettext_lazy('Version'), max_length=200, default='trunk')
    status = models.CharField(gettext_lazy('Status'), max_length=20, choices=bug_status_choices, default='open')
    modifier = models.ForeignKey(User)
    bug = models.ForeignKey(Bug)
    last_modified=models.DateTimeField(gettext_lazy('Last Modify Time'), auto_now=True, editable=False)
    created=models.DateTimeField(gettext_lazy('Create Time'), auto_now_add=True, editable=False)
    def __unicode__(self):
        return self.summary+' - ' + str(self.created);
    class Admin:
        pass;
    class Meta:
        verbose_name = gettext_lazy('Content');
        verbose_name_plural = gettext_lazy('Contents');
        ordering = ['-last_modified']

py/oa-gae/branches/django/site_improve/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic import list_detail, create_update
from django.http import HttpResponse  
import datetime
from django.template import RequestContext
from oa.site_improve.models import Bug,Content
from django import newforms as forms
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.decorators import login_required

from oa.templatetags import title_field_html

class BugForm(forms.ModelForm):
    class Meta:
        model=Content
        exclude = ('bug','version','modifier',)

@login_required
def bug_edit(request):
    if request.GET and request.GET.has_key('id'):
        id = request.GET['id']
        bug = get_object_or_404(Bug, pk=id)
        f = BugForm(instance=bug.current_content)
        return render_to_response('site_improve/bug_form.html', {'form':f, "submit_times":-1, 'display_cancel':'true', 'id':id}, context_instance=RequestContext(request))
    else:
        f = BugForm()
        return render_to_response('site_improve/bug_form.html', {'form':f, "submit_times":-1, 'display_cancel':'true'}, context_instance=RequestContext(request))
    
@login_required
def bug_index(request):
    if request.method == 'GET':
        pageSize = int(request.GET.get('pageSize',settings.DEFAUTL_PAGE_SIZE))
        pageNum = long(request.GET.get('pageNum',1))
        order_str = title_field_html.get_order_str(request)
        queryset = Bug.objects.filter()
        if order_str:
            queryset = queryset.order_by(order_str)
        return list_detail.object_list(request, 
                               queryset = queryset,
                               paginate_by=pageSize,
                               page=pageNum)  
    elif request.method == 'POST':
        f = BugForm(request.POST, request.FILES)
        if f.is_valid():
            bug = Bug()
            bug.save()
            content = f.save(commit=False)
            content.modifier = request.user
            content.bug = bug
            content.save()
            bug.current_content = content
            bug.save()
            return HttpResponseRedirect(bug.id)
        else:
            return render_to_response('site_improve/bug_form.html', {'form':f,"submit_times":int(request.POST['submit_times']) - 1,'display_cancel':request.POST.get('display_cancel','true')},context_instance=RequestContext(request))
    raise Http404

@login_required
def bug_my(request):
    pageSize = int(request.GET.get('pageSize',settings.DEFAUTL_PAGE_SIZE))
    pageNum = long(request.GET.get('pageNum',1))
    order_str = title_field_html.get_order_str(request)
    queryset = Bug.objects.filter(current_content__modifier=request.user)
    if order_str:
        queryset = queryset.order_by(order_str)
    return list_detail.object_list(request, 
                           queryset = queryset,
                           paginate_by=pageSize,
                           page=pageNum)  

@login_required
def bug_open(request):
    pageSize = int(request.GET.get('pageSize',settings.DEFAUTL_PAGE_SIZE))
    pageNum = long(request.GET.get('pageNum',1))
    order_str = title_field_html.get_order_str(request)
    queryset = Bug.objects.filter(current_content__status='open')
    if order_str:
        queryset = queryset.order_by(order_str)
    return list_detail.object_list(request, 
                           queryset = queryset,
                           paginate_by=pageSize,
                           page=pageNum)  

@login_required
def bug_detail(request,object_id):
    if request.method == 'GET':
        return list_detail.object_detail(request,queryset= Bug.objects.all(),object_id=object_id)
    elif request.method == 'POST':
        method = request.POST.get(settings.EXTEND_HTTP_METHOD,None) 
        if method == 'PUT':
            bug = get_object_or_404(Bug,pk=object_id)
            f = BugForm(request.POST, request.FILES)
            if f.is_valid():
                content = f.save(commit=False)
                content.modifier = request.user
                content.bug = bug
                content.save()
                bug.current_content = content
                bug.save()
                return HttpResponseRedirect(object_id)
            else:
                return render_to_response('site_improve/bug_form.html', {'form':f,"submit_times":int(request.POST['submit_times'])-1,'id':object_id,'display_cancel':request.POST.get('display_cancel','true')},context_instance=RequestContext(request))
        elif method == 'DELETE':
            if not request.user.is_staff:
                raise Http404
            return create_update.delete_object(request,model=Bug,object_id=object_id,post_delete_redirect='./')
    raise Http404
        

py/oa-gae/branches/django/site_improve/templates/site_improve/bug_detail.html
{% extends "base/base_detail.html" %}
{% load i18n %}
{% block title %}查看建议{% endblock %}
{% block viewHead %} {% endblock %}

{% block viewBody %}
{% include "site_improve/lib/left.html" %}
<form name="deleteForm" action="" method="POST">
<input type="hidden" name="__http_method" value="DELETE"/>
</form>
<div id=“container” style="width:88%;float:right;">
<table class="main" summary="view Table">
	<caption>建议详细信息</caption>
	<thead>
		<th colspan="2"></th>
	</thead>
</table>

{% for content in object.content_set.all %}
<table class="main" summary="view Table">
	<thead>
		<th colspan="2">{% ifequal content.id object.current_content.id %} 当前版本 {% endifequal %} {{ content.created }} editted by {% if content.modifier.first_name %}{{content.modifier.last_name|escape}}{{ content.modifier.first_name|escape }}{% else %}{{ content.modifier.username }}{% endif %}</th>
	</thead>
	<tbody>
		<tr>
			<th>{% trans 'Summary' %}:</th>
			<td>{{ content.summary }}</td>
		</tr>
		<tr>
			<th>{% trans 'Type' %}:</th>
			<td>{% trans content.type %}</td>
		</tr>
		<tr>
			<th>{% trans 'Priority' %}:</th>
			<td>{% trans content.priority %}</td>
		</tr>
		<tr>
			<th>{% trans 'Assign to' %}:</th>
			<td>{{ content.assign_to }}</td>
		</tr>		
		<tr>
			<th>{% trans 'Cc' %}:</th>
			<td>{{ content.cc }}</td>
		</tr>
		<tr>
			<th>{% trans 'Keywords' %}:</th>
			<td>{{ content.keywords }}</td>
		</tr>
		<tr>
			<th>{% trans 'component' %}:</th>
			<td>{% trans content.component %}</td>
		</tr>
		<tr>
			<th>{% trans 'Version' %}:</th>
			<td>{{ content.version }}</td>
		</tr>
		<tr>
			<th>{% trans 'Status' %}:</th>
			<td>{% trans content.status %}</td>
		</tr>
		<tr>
			<th>{% trans 'Content' %}:</th>
			<td>{{ content.content }}</td>
		</tr>
	</tbody>
</table>
{% endfor %}

<table class="main" summary="view Table">
	<tfoot>
		<th colspan="2">
			<a href="Javascript:self.location.href='./'">建议列表</a>
			<a href="!edit?id={{ object.id }}">编辑</a>
			<a href="Javascript:bupticetCommon.deleteConfirmUseForm('{{ object.id }}')">删除</a>
		</th>
	</tfoot>
</table>	
</div>
{% include "site_improve/lib/right.html" %}
{% endblock %}

py/oa-gae/branches/django/site_improve/templates/site_improve/bug_form.html
{% extends "base/base_form.html" %}
{% load i18n %}
{% block title %}编辑站点改进建议{% endblock %}
{% block editHead %}
<script type="text/javascript">
window.onload=function(){
	var oldOnsubmit = document.forms['form'].onsubmit;
	document.forms['form'].onsubmit = function(){
		var check = oldOnsubmit(); 
		var check2 = true;
		form = document.forms['form'];
		if(check&&check2){
			bupticetCommon.emptyOnUnload();
			bupticetCommon.disableSubmit();
			return true;
		}else{
			return false;
		}
	}
	document.forms['form'].elements['summary'].focus();
}
</script>
{% endblock %}  

{% block editBody %}
{% include "site_improve/lib/left.html" %}  
<form name="form" action="./{{ id }}" method="POST" onsubmit="return true;">
<input type="hidden" name="submit_times" value="{{ submit_times }}"/>
<input type="hidden" name="ext_query_str" value="{{ ext_query_str }}"/>
{% if id %}
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="__http_method" value="PUT"/>
{% endif %}
<table class="main" summary="Edit Table">
<caption>编辑站点改进建议</caption>
<thead>
<th colspan="2">
</th>
</thead>
<tfoot>
<th colspan="2">
{% include "lib/form_buttons.html" %} 
</th>
</tfoot>
<tbody>

{{ form.as_table }}

</tbody>
</table>
</form>
{% include "site_improve/lib/right.html" %}
{% endblock %}

py/oa-gae/branches/django/site_improve/templates/site_improve/bug_list.html
{% extends "base/base_list.html" %}
{% load i18n %}
{% load ext_query_string %}
{% load media %}
{% load theme %}
{% load context_path %}
{% load title_field_html %}
{% block title %}建议列表{% endblock %}
{% block listHead %}

{% endblock %}  

{% block listBody %}
{% include "site_improve/lib/left.html" %}
<form name="deleteForm" action="" method="POST">
<input type="hidden" name="__http_method" value="DELETE"/>
</form>
<table class="main" summary="List Table">
	<caption>建议列表</caption>
	<thead>
		<th width="30">序号</th>
		<th>{% title_field_html "current_content__summary" "Summary" %}</th>
		<th width="50">{% title_field_html "current_content__type" "Type" %}</th>
		<th width="50">{% title_field_html "current_content__priority" "Priority" %}</th>
		<th width="80">{% title_field_html "current_content__component" "Component" %}</th>
		<th width="50">{% title_field_html "current_content__status" "Status" %}</th>
		<th width="100">操作</th>
	</thead>
	<tfoot>
		<th colspan="7">{% include "lib/paginator.html" %}</th>
	</tfoot>
	<tbody>
{% for object in object_list %}
		<tr title="双击此行查看详细内容"
			ondblclick="Javascript:self.location.href='{% context_path %}/site_improve/{{ object.id }}'">
			<td>{{ first_on_page|add:forloop.counter0 }}</td>
			<td class="left"><a href="{% context_path %}/site_improve/{{ object.id }}">{{ object.current_content.summary }}</a></td>
			<td>{% trans object.current_content.type %}</td>
			<td>{% trans object.current_content.priority %}</td>
			<td>{% trans object.current_content.component %}</td>
			<td>{% trans object.current_content.status %}</td>			
			<td>
			<a href="{{ object.id }}">查看</a>
			<a href="{% context_path %}/site_improve/!edit?id={{ object.id }}">编辑</a>
{% if user.is_staff %}			
			<a href="Javascript:bupticetCommon.deleteConfirmUseForm('{% context_path %}/site_improve/{{ object.id }}')">删除</a>
{% endif %}
			</td>
		</tr>
{% endfor %}
{% if results_per_page %}
{% load repeat %}{% repeat results_per_page object_list|length %}<tr>
	<td colspan="7">&nbsp;</td>
</tr>
{% endrepeat %}
{% endif %}
	</tbody>
</table>
{% include "site_improve/lib/right.html" %}
{% endblock %}